blank_issues_enabled: true
contact_links:
- name: Questions
  url: https://github.com/KoreanGRF/KoreanTrainSet/discussions/categories/%EC%A7%88%EB%AC%B8-q-a
  about: Ask questions for Korean Train Set.
